dist: xenial  # required for python >= 3.7
language: python
python:
  - "3.8"
install:
  - pip install poetry
  - poetry --version
  - poetry install
  - poetry run python -V
script:
  - poetry run black -l 79 . --check
  - poetry run make all
